import type { Metadata } from "next";
import { century, ovo, bigCaslon, creatorsType } from "@/lib/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${century.variable} ${ovo.variable}   ${bigCaslon.variable}
    ${creatorsType.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
